# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1av6oz_1mP2N1JprvFcnz0W7m0GolQauZ
"""

numbers = list(map(float, input("Enter numbers separated by space: ").split())) # input number as a string then splitting to a a list of float numbers
sum_of_numbers = sum(numbers)
average = sum_of_numbers / len(numbers)
print("Sum:", sum_of_numbers)
print("Average:", average)